import os
os.system('python ./installers/quick_faucet_installer.py')
os.system('python ./installers/docker_installer.py')
os.system('python ./installers/poseidon_installation.py')
os.system('sudo apt-get install openvswitch-switch')
os.system('cd /usr/bin')
os.system('sudo wget https://raw.githubusercontent.com/openvswitch/ovs/master/utilities/ovs-docker')
os.system('sudo chmod a+rwx ovs-docker')
os.system('sudo apt install net-tools')
os.system('sudo snap install docker')